"""Genera el DDL del esquema actual (solo tablas de Despacho Campo) desde el catálogo.

Uso (desde backend/):  python -m scripts.exportar_esquema > sql/migrations/0001_esquema_base.sql

No requiere pg_dump. Excluye tablas ajenas que conviven en la misma base.
"""

from __future__ import annotations

import sys

from app.crud import ALLOWED_TABLES
from app.db import get_conn

TABLAS = sorted(ALLOWED_TABLES)


def main() -> None:
    out: list[str] = [
        "-- Esquema base de Despacho Campo (generado desde el catálogo de Postgres).",
        "-- Aplicar solo sobre una base vacía; en la base existente se marca como aplicado.",
        "",
        "SET client_min_messages = warning;",
        "",
    ]
    with get_conn(write=False) as conn:
        cur = conn.cursor()

        # Todas las funciones propias del esquema (no las de extensiones). Incluye las
        # auxiliares que llaman los triggers (p. ej. nombre_desde_codigo_modulo): Postgres
        # no valida el cuerpo al crear la función, así que omitirlas rompería recién al insertar.
        # Primero SQL (auxiliares), luego plpgsql (triggers).
        cur.execute(
            """
            SELECT p.proname, pg_get_functiondef(p.oid) AS def
            FROM pg_proc p
            JOIN pg_namespace n ON n.oid = p.pronamespace
            JOIN pg_language l ON l.oid = p.prolang
            WHERE n.nspname = 'public'
              AND p.prokind = 'f'
              AND NOT EXISTS (
                SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e'
              )
            ORDER BY (l.lanname <> 'sql'), p.proname
            """
        )
        funciones = cur.fetchall()
        out.append("-- ---------- Funciones")
        for f in funciones:
            out.append(f["def"].strip() + ";\n")

        # Tablas (sin FKs; se agregan al final para no depender del orden)
        out.append("-- ---------- Tablas")
        for tabla in TABLAS:
            cur.execute(
                """
                SELECT a.attname AS col,
                       format_type(a.atttypid, a.atttypmod) AS tipo,
                       a.attnotnull AS notnull,
                       a.attidentity AS identidad,
                       pg_get_expr(d.adbin, d.adrelid) AS defecto
                FROM pg_attribute a
                JOIN pg_class c ON c.oid = a.attrelid
                JOIN pg_namespace n ON n.oid = c.relnamespace
                LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
                WHERE n.nspname = 'public' AND c.relname = %s AND a.attnum > 0 AND NOT a.attisdropped
                ORDER BY a.attnum
                """,
                (tabla,),
            )
            columnas = cur.fetchall()
            if not columnas:
                continue
            defs = []
            for col in columnas:
                tipo = col["tipo"]
                defecto = col["defecto"] or ""
                if defecto.startswith("nextval("):
                    tipo = {"integer": "serial", "bigint": "bigserial", "smallint": "smallserial"}.get(tipo, tipo)
                    defecto = ""
                linea = f'    {col["col"]} {tipo}'
                if col["identidad"] == "a":
                    linea += " GENERATED ALWAYS AS IDENTITY"
                elif col["identidad"] == "d":
                    linea += " GENERATED BY DEFAULT AS IDENTITY"
                if col["notnull"]:
                    linea += " NOT NULL"
                if defecto:
                    linea += f" DEFAULT {defecto}"
                defs.append(linea)

            cur.execute(
                """
                SELECT con.conname, pg_get_constraintdef(con.oid) AS def
                FROM pg_constraint con
                JOIN pg_class c ON c.oid = con.conrelid
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = 'public' AND c.relname = %s AND con.contype IN ('p', 'u', 'c')
                ORDER BY con.contype DESC, con.conname
                """,
                (tabla,),
            )
            for con in cur.fetchall():
                defs.append(f'    CONSTRAINT {con["conname"]} {con["def"]}')
            out.append(f"CREATE TABLE {tabla} (\n" + ",\n".join(defs) + "\n);\n")

        out.append("-- ---------- Llaves foráneas")
        cur.execute(
            """
            SELECT c.relname AS tabla, con.conname, pg_get_constraintdef(con.oid) AS def
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public' AND c.relname = ANY(%s) AND con.contype = 'f'
            ORDER BY c.relname, con.conname
            """,
            (TABLAS,),
        )
        for fk in cur.fetchall():
            out.append(f'ALTER TABLE {fk["tabla"]} ADD CONSTRAINT {fk["conname"]} {fk["def"]};')
        out.append("")

        out.append("-- ---------- Índices (los de PK/UNIQUE ya los crean sus restricciones)")
        cur.execute(
            """
            SELECT i.indexname, i.indexdef
            FROM pg_indexes i
            WHERE i.schemaname = 'public' AND i.tablename = ANY(%s)
              AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conname = i.indexname)
            ORDER BY i.tablename, i.indexname
            """,
            (TABLAS,),
        )
        for idx in cur.fetchall():
            out.append(idx["indexdef"] + ";")
        out.append("")

        out.append("-- ---------- Triggers")
        cur.execute(
            """
            SELECT pg_get_triggerdef(t.oid) AS def
            FROM pg_trigger t
            JOIN pg_class c ON c.oid = t.tgrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public' AND NOT t.tgisinternal AND c.relname = ANY(%s)
            ORDER BY c.relname, t.tgname
            """,
            (TABLAS,),
        )
        for trg in cur.fetchall():
            out.append(trg["def"] + ";")
        out.append("")

    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
